export const actionTypes={
     ALL_EMAIL : "ALL_EMAIL",
     SINGLE_EMAIL:"SINGLE_EMAIL",
     PAGED_EMAILS:"PAGED_EMAILS",
     CURRENT_EMAIL:"CURRENT_EMAIL",
     FAVORITE_EMAIL:"FAVORITE_EMAIL",
     READED_EMAIL:"READED_EMAIL",
     READ_FILTER:"READ_FILTER",
     FAVORITE_FILTER:"FAVORITE_FILTER",
     UNREAD_FILTER:"UNREAD_FILTER",
     RESET_FILTERTYPE:"RESET_FILTERTYPE"
}